<script lang="ts">
	import { gptQuestions } from '$lib/questions';
	// Svelte related
	import { useChat } from 'ai/svelte';
	import { enhance, applyAction } from '$app/forms';

	const { messages, handleSubmit, input } = useChat({
		api: '/api/chat-bot/'
	});

	let rateLimitError = '';
	let selectedValue = '';
	let selectEvent: null | Event = null;
	let buttonIsDisabled = true;
	let acknowledged = false;

	async function handleSelect(e: Event) {
		$input = selectedValue;
		selectEvent = e;
		buttonIsDisabled = false;
	}
</script>

<section
	class="p-5 mx-auto container md:w-4/5 flex flex-col card relative variant-ghost-secondary gap-4 justify-center items-center"
>
	<h2 class="text-2xl sm:text-3xl sm:leading-3xl font-bold text-surface-500 leading-2xl p-2">
		GPT Bot Interview.
	</h2>
	<p class="text-xl leading-xl bold md:w-3/4 text-center mx-auto">
		Ask GPT a question to learn about me. Choose from a list of questions to find more about me and
		my career journey.
	</p>
	<div class="variant-glass-secondary p-4 card text-surface-800 sm:w-4/5">
		<p>
			Note: This is a fun feature showcasing my third-party integration skills. While I've curated
			and guided prompts for better results, the final replies come from GPT and I have no control
			over them.. Enjoy!
		</p>
		<div class="flex justify-center pt-4">
			<input
				class="card mr-2 mt-1 variant-glass-secondary"
				type="checkbox"
				id="acknowledge"
				name="acknowledge"
				bind:checked={acknowledged}
			/>
			<label class="text-surface-800" for="acknowledge"
				>I acknowledge any information given is generated by GPT and the accuracy of the information
				can't be guaranteed.
			</label>
		</div>
	</div>
	<!-- // See  InteractiveCV.README -->
	{#if rateLimitError}
		<p class="variant-filled-error p-4 card">{rateLimitError}</p>
	{/if}
	{#if acknowledged && !rateLimitError}
		<form
			method="POST"
			use:enhance={() => {
				buttonIsDisabled = true;
				return async ({ result }) => {
					if (result?.type === 'success') {
						handleSubmit(selectEvent);
					}
					if (result?.type === 'failure') {
						rateLimitError =
							'Rate limit is restricted to 3 requests per 15 minutes during testing. Please try again later.';
					}
					if (result?.type === 'error') {
						await applyAction(result);
					}
				};
			}}
			class="flex flex-col justify-center items-center gap-4 w-full"
		>
			<label class="text-lg" for="questions">Bot Question</label>
			<select
				bind:value={selectedValue}
				on:change={(e) => handleSelect(e)}
				name="questions"
				id="questions"
				class="w-1/2 variant-glass-secondary card"
			>
				<option value="">--Select a question--</option>
				<option value={`${gptQuestions['art-dev'][1]}`}>{gptQuestions['art-dev'][0]} </option>
				<option value={`${gptQuestions['vue-certification'][1]}`}
					>{gptQuestions['vue-certification'][0]}
				</option>
			</select>
			{#if selectedValue}
				<button disabled={buttonIsDisabled} class="btn variant-soft-primary">Submit Question</button
				>
			{/if}
		</form>
	{/if}
	<div class="mx-auto variant-glass card w-full p-4 gap-4 flex flex-col">
		{#if selectedValue}
			<h4 class="text-xl leading-2xl font-bold text-center">Question: {$input}</h4>
		{/if}
		<div class="[&>*:nth-child(odd)]:font-bold [&>*:nth-child(even)]:pb-2">
			{#each $messages as message}
				<p>{message?.content}</p>
			{/each}
		</div>
	</div>
</section>
