<script>
	import * as feather from 'feather-icons';

	const bagIconSvg = feather.icons['shopping-bag'].toSvg({
		stroke: '#d7424b',
		width: 28,
		height: 28
	});
	const lockIconSvg = feather.icons['lock'].toSvg({
		stroke: '#d7424b',
		width: 28,
		height: 28
	});
	const awardIconSvg = feather.icons['award'].toSvg({
		stroke: '#d7424b',
		width: 28,
		height: 28
	});
	const bookIconSvg = feather.icons['book-open'].toSvg({
		stroke: '#d7424b',
		width: 28,
		height: 28
	});
</script>

<div class="container mx-auto pt-2 flex gap-4 flex-col">
	<div
		class="card relative p-4 variant-soft-secondary flex flex-col gap-4 justify-center items-center"
	>
		<h2 class="text-2xl sm:text-3xl sm:leading-3xl font-bold text-surface-500 leading-2xl p-2">
			GPT Bot Interview.
		</h2>
		<p class="m-auto"><span class="variant-filled-success card p-2">COMING SOON</span></p>
		<p class="text-xl leading-3xl bold sm:w-3/4 text-center">
			Ask GPT a question to learn about me. Choose from a list of questions to find more about me
			and my career journey.
		</p>
		<div class="variant-glass-secondary p-4 card text-surface-800 sm:w-2/3">
			<p>
				Note: This is a fun feature showcasing my third-party integration skills. While I've curated
				resume-specific responses for accuracy, general replies come from GPT and I have no control
				over. All GPT responses are in <span class="italic">italics</span> for clarity. Enjoy!
			</p>

			<div class="flex justify-center pt-4">
				<input
					class="card mr-2 mt-1 variant-glass-secondary"
					type="checkbox"
					id="acknowledge"
					name="acknowledge"
				/>
				<label class="text-surface-800" for="acknowledge"
					>I acknowledge any information given in italics is generated by GPT and the accuracy of
					the information can't be guaranteed
				</label>
			</div>
		</div>
		<label class="bold text-xl opacity-30" for="questions">Coming soon! </label>
		<select disabled name="questions" id="questions" class="w-1/2 variant-glass-secondary card">
			<option value="">--Feature coming soon....--</option>
			<option value="dog">Dog</option>
			<option value="cat">Cat</option>
			<option value="hamster">Hamster</option>
			<option value="parrot">Parrot</option>
			<option value="spider">Spider</option>
			<option value="goldfish">Goldfish</option>
		</select>
	</div>
	<div class="variant-filled-ghost card p-4">
		<h3
			class="uppercase font-bold text-2xl sm:text-3xl sm:leading-3xl leading-3xl text-center pb-4 rounded"
		>
			CV Summary
		</h3>

		<div class="grid sm:grid-cols-2 gap-4 sm:gap-8">
			<div class="flex flex-col items-center p-4 card variant-glass">
				<div class="py-2">{@html bagIconSvg}</div>
				<p class="text-center">
					Developer on Famous Footwear for Caleres, a Fortune 1000 company. Developed custom and
					highly visible landing pages for notable brands including Nike and Converse.
				</p>
			</div>
			<div class="flex flex-col items-center p-4 card variant-glass">
				<div class="py-2">{@html lockIconSvg}</div>
				<p class="text-center">
					Sole front-end developer for a small 3 person team (Power Admin) which relied upon me to
					create UIs for server monitoring software.
				</p>
			</div>
			<div class="flex flex-col items-center p-4 card variant-glass">
				<div class="py-2">{@html awardIconSvg}</div>
				<p class="text-center">
					Proactively contributes to innovative solutions and practical improvements. Delivers
					consistent, high-quality results. Keeps current and actively creates and maintains
					personal projects.
				</p>
			</div>
			<div class="flex flex-col items-center p-4 card variant-glass">
				<div class="py-2">{@html bookIconSvg}</div>
				<p class="text-center">
					Demonstrated consistent technical progression. Evolved from design, to CSS/Layout/jQuery,
					to sole front-end developer of applications, and to full-stack contributions.
				</p>
			</div>
		</div>
	</div>
</div>
