<script lang="ts">
	import { useChat } from 'ai/svelte';
	import { gptQuestions } from '$lib/questions';

	const { messages, handleSubmit, input } = useChat({ api: '/api/chat-bot/' });
</script>

<div class="container mx-auto pt-2 flex gap-4 flex-col">
	<div
		class="card relative p-4 variant-soft-secondary flex flex-col gap-4 justify-center items-center"
	>
		<h2 class="text-2xl sm:text-3xl sm:leading-3xl font-bold text-surface-500 leading-2xl p-2">
			GPT Bot Interview.
		</h2>
		<p class="m-auto"><span class="variant-filled-success card p-2">COMING SOON</span></p>
		<p class="text-xl leading-3xl bold sm:w-3/4 text-center">
			Ask GPT a question to learn about me. Choose from a list of questions to find more about me
			and my career journey.
		</p>
		<div class="variant-glass-secondary p-4 card text-surface-800 sm:w-2/3">
			<p>
				Note: This is a fun feature showcasing my third-party integration skills. The questions are
				designed to be generic inqueries concerning anyone with my skillset. While I've made an
				effort to influence some of the responseses for accuracy, I, Aaron Happe, have no control
				over the final response.
			</p>

			<div class="flex justify-center pt-4">
				<input
					class="card mr-2 mt-1 variant-glass-secondary"
					type="checkbox"
					id="acknowledge"
					name="acknowledge"
				/>
				<label class="text-surface-800" for="acknowledge"
					>I acknowledge any information given is generated by GPT and the accuracy of the
					information can't be guaranteed.
				</label>
			</div>
		</div>
		<label class="bold text-xl opacity-30" for="questions">Coming soon! </label>
		<select
			bind:value={$input}
			on:change={handleSubmit}
			name="questions"
			id="questions"
			class="w-1/2 variant-glass-secondary card"
		>
			<option value="">--Feature coming soon....--</option>
			<option value="art-dev">{gptQuestions['art-dev']} </option>
			<option value="vue-certification">{gptQuestions['vue-certification']}</option>
		</select>
		<ul>
			{#each $messages as message, index}
				{#if index === 1}
					<li>{message.content}</li>
				{/if}
			{/each}
		</ul>
	</div>
</div>
