<script lang="ts">
	import { gptQuestions } from '$lib/questions';
	import { useChat } from 'ai/svelte';

	const { messages, handleSubmit, input } = useChat({
		api: '/api/chat-bot/'
	});

	let selectedValue = '';

	function handleSelect(e: Event) {
		$input = selectedValue;
		handleSubmit(e);
	}
</script>

<section
	class="p-5 mx-auto container md:w-4/5 flex flex-col card relative variant-ghost-secondary gap-4 justify-center items-center"
>
	<h2 class="text-2xl sm:text-3xl sm:leading-3xl font-bold text-surface-500 leading-2xl p-2">
		GPT Bot Interview.
	</h2>
	<p class="text-xl leading-xl bold md:w-3/4 text-center mx-auto">
		Ask GPT a question to learn about me. Choose from a list of questions to find more about me and
		my career journey.
	</p>
	<div class="variant-glass-secondary p-4 card text-surface-800 sm:w-4/5">
		<p>
			Note: This is a fun feature showcasing my third-party integration skills. While I've curated
			and guided prompts for better results, the final replies come from GPT and I have no control
			over them.. Enjoy!
		</p>
		<div class="flex justify-center pt-4">
			<input
				class="card mr-2 mt-1 variant-glass-secondary"
				type="checkbox"
				id="acknowledge"
				name="acknowledge"
			/>
			<label class="text-surface-800" for="acknowledge"
				>I acknowledge any information given in italics is generated by GPT and the accuracy of the
				information can't be guaranteed.
			</label>
		</div>
	</div>
	<label class="bold text-xl opacity-30" for="questions">Coming soon! </label>
	<select
		bind:value={selectedValue}
		on:change={(e) => handleSelect(e)}
		name="questions"
		id="questions"
		class="w-1/2 variant-glass-secondary card"
	>
		<option value="">--Feature coming soon....--</option>
		<option value={`${gptQuestions['art-dev'][1]}`}>{gptQuestions['art-dev'][0]} </option>
		<option value={`${gptQuestions['vue-certification'][1]}`}
			>{gptQuestions['vue-certification'][0]}
		</option>
		<!-- <option value={`${gptQuestions['vue-certification']}`}
    >{gptQuestions['vue-certification']}</option
  > -->
	</select>
	<div class="mx-auto variant-glass card w-full p-4 gap-4 flex flex-col">
		<h4 class="text-2xl leading-2xl font-bold">Answers: {$input}</h4>
		<div class="[&>*:nth-child(odd)]:font-bold [&>*:nth-child(even)]:pb-2">
			{#each $messages as message}
				<p>{message.content}</p>
			{/each}
		</div>
	</div>
</section>
