<script lang="ts">
	import { getModalStore } from '@skeletonlabs/skeleton';
	// Skeleton Types
	import type { ModalSettings } from '@skeletonlabs/skeleton';
	// Firebase related
	import { auth } from '$lib/firebaseClient';
	import { userStore } from 'sveltefire';

	const modalStore = getModalStore();

	let signedIn = false;

	const user = userStore(auth);

	function showSignInModal() {
		const modal: ModalSettings = {
			type: 'component',
			// Pass the component registry key as a string:
			component: 'signIn'
		};
		modalStore.trigger(modal);
	}
</script>

<section
	class="p-4 container mx-auto flex flex-col card relative variant-ghost-secondary gap-4 justify-center items-center"
>
	{#if !$user?.uid}
		<h2 class="text-2xl sm:text-3xl sm:leading-3xl font-bold text-surface-500 leading-2xl p-2">
			GPT Bot Interview.
		</h2>

		<h3 class="text-2xl italic text-primary-500">White listed feature.</h3>
		<p class="text-xl">Have access?</p>
		<button on:click={showSignInModal} class="btn variant-ghost-primary">Sign In</button>
		<p class="text-xl">
			Want access? <span class="text-surface-900 underline">request it.</span>
		</p>
	{:else}
		<div>
			<p class="text-xl leading-3xl bold sm:w-3/4 text-center">
				Ask GPT a question to learn about me. Choose from a list of questions to find more about me
				and my career journey.
			</p>
			<div class="variant-glass-secondary p-4 card text-surface-800 sm:w-2/3">
				<p>
					Note: This is a fun feature showcasing my third-party integration skills. While I've
					curated resume-specific responses for accuracy, general replies come from GPT and I have
					no control over. All GPT responses are in <span class="italic">italics</span> for clarity.
					Enjoy!
				</p>
				<div class="flex justify-center pt-4">
					<input
						class="card mr-2 mt-1 variant-glass-secondary"
						type="checkbox"
						id="acknowledge"
						name="acknowledge"
					/>
					<label class="text-surface-800" for="acknowledge"
						>I acknowledge any information given in italics is generated by GPT and the accuracy of
						the information can't be guaranteed
					</label>
				</div>
			</div>
			<label class="bold text-xl opacity-30" for="questions">Coming soon! </label>
			<select disabled name="questions" id="questions" class="w-1/2 variant-glass-secondary card">
				<option value="">--Feature coming soon....--</option>
				<option value="dog">Dog</option>
				<option value="cat">Cat</option>
				<option value="hamster">Hamster</option>
				<option value="parrot">Parrot</option>
				<option value="spider">Spider</option>
				<option value="goldfish">Goldfish</option>
			</select>
		</div>
	{/if}
</section>
